### ISSUE TITLE
Link background/highlight doesn't work on links that have `code` in them

### ISSUE THREAD

**Issue by lf-** [niklasmtj/gatsby-starter-julia#20]
![image](https://user-images.githubusercontent.com/6652840/86559995-2b00a300-bf12-11ea-9583-1e4f1e919398.png)

I made it purple so it's more visible. If the link target is put in backticks like so: ```[`example.com`](https://example.com)```, then the link highlighting is not visible. Ideally the coloured highlight would be in front of the code background but behind the text.

**Comment by niklasmtj** [comment]
Hey, 
I will try to get a look into it in the next couple of days.

**Comment by niklasmtj** [comment]
Hey @lf- ,
I looked into it. Sorry to say but I will not integrate it like that in this GatsbyJS starter. Displaying the same effect of the link in a `code` block would look very cluttered in my opinion.
This would not look good from a design perspective in my opinion. 

What I will add to `code` inside a link is a `text-decoration: underline` when hovering the link to signaling that this element is a link. Otherwise it is not clear that it is a link if it only consists of a `code` element.
Like so:
<img width="212" alt="grafik" src="https://user-images.githubusercontent.com/22395665/86788022-ff8ecd00-c065-11ea-8ad8-b7ddad2d549c.png">

Fortunately this is an Open Source project and you are free to fork this starter to make it your own!  

If you want to change it you have to keep in mind that the hover effect works with a background-image. The `code` block will add `background-color` and will change `background-image` to `none` to the text inside the backticks. 
Try adding at the bottom of the `layout.css` file the following lines:
```css
a > code {
  position: relative !important;
  background-image: linear-gradient(
    rgba(255, 250, 150, 0.8),
    rgba(255, 250, 150, 0.8)
  ) !important;
  background-repeat: no-repeat !important;
  background-size: 100% 0.2em !important;
  background-position: 0 88% !important;
}
```
`!important` is used because otherwise `prismjs` will overwrite it with the code theme background settings of `background-image: none`

I hope I was able to help you,
Niklas
